\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={STAT 587 - Homework 1},
            pdfauthor={Martin Simonson},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{STAT 587 - Homework 1}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Martin Simonson}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{January 25, 2019}


\begin{document}
\maketitle

\section{1.) SAT Mathematics Scores}\label{sat-mathematics-scores}

A person claims that the current SAT Mathematics (SATM) test scores are
over-estimates of the ability of typical high school seniors because not
all students take the test. They further claim that if the test became
required for all seniors, the mean score would be no more than 450.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  H\textsubscript{0}: The mean SATM score = 450;
\item
  H\textsubscript{a}: The mean SATM score \neq 450
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.stat<-((}\FloatTok{460.56}\OperatorTok{-}\DecValTok{450}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\FloatTok{98.65}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{500}\NormalTok{)))}
\NormalTok{t<-}\KeywordTok{round}\NormalTok{(test.stat,}\DecValTok{3}\NormalTok{)}
\NormalTok{t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.394
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The test statistic is 2.394 with 499 degrees of freedom
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p<-}\KeywordTok{round}\NormalTok{((}\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(}\OperatorTok{-}\KeywordTok{abs}\NormalTok{(t),}\DataTypeTok{df=}\DecValTok{499}\NormalTok{)),}\DecValTok{3}\NormalTok{)}
\NormalTok{p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.017
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value from the t-table for a one-tailed test with a t-statistic
  of 2.394 with 499 degrees of freedom is bounded between .01 and .005,
  and the exact p-value as calculated by R is 0.017.
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Given the sample data we can conclude that there is \emph{some}
  evidence to reject the null hypothesis and support the alternative
  hypothesis that the mean SATM test scores are no more than 450.
\end{itemize}

\section{2.) Something Fishy in the Cheese
Factory}\label{something-fishy-in-the-cheese-factory}

Cheese admins suspect that their milk supplier is watering down milk to
increase profits. The freezing point of natural milk is
\(-0.545^{\circ}C\). Adding water will raise the freezing temperature.
The freezing temperature of 15 lots of suppliers milk is measured. The
average of the 15 measurements is \(\bar{X} = -0.538^{\circ}C\) with
standard deviation of \(s = 0.008^{\circ}C\). Is this sufficient
statistical evidence that the supplier is adding water to the milk?

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  H\textsubscript{0}: The freezing point of the supplier's milk =
  \(-0.545^{\circ}C\);
\item
  H\textsubscript{a}: The freezing point of the supplier's milk
  \textgreater{} \(-0.545^{\circ}C\)
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.stat<-((}\OperatorTok{-}\NormalTok{.}\DecValTok{538}\OperatorTok{-}\StringTok{ }\OperatorTok{-}\NormalTok{.}\DecValTok{545}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\FloatTok{0.008}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(}\DecValTok{15}\NormalTok{)))}
\NormalTok{t<-}\KeywordTok{round}\NormalTok{(test.stat,}\DecValTok{3}\NormalTok{)}
\NormalTok{t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.389
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The test statistic is 3.389 with 14 degrees of freedom
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p<-}\KeywordTok{round}\NormalTok{((}\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(}\OperatorTok{-}\KeywordTok{abs}\NormalTok{(t),}\DataTypeTok{df=}\DecValTok{14}\NormalTok{)),}\DecValTok{3}\NormalTok{)}
\NormalTok{p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.004
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The p-value from the t-table for a one-tailed test with a t-statistic
  of 3.389 with 14 degrees of freedom is bounded between 0.005 and and
  0.001, and the exact p-value as calculated by R is 0.004.
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Given this sample data we can conclude that there is strong evidence
  to reject the null hypothesis that the supplier's milk freezes at the
  same temperature as natural milk and supports the alternative
  hypothesis that the supplier's milk is watered down and freezes at a
  higher temperature than \(-0.545^{\circ}C\).
\end{itemize}

\section{3.) VW Gas Mileage}\label{vw-gas-mileage}

The VW's on-board computer was reading a better mile per gallon (MPG)
than advertised for that model. Therefore, the computer's MPG and
driver-recorded MPG recorded for each fill-up in 2016. The data provided
in \emph{mpg.txt} shows the differences between the computer's MPG
calculations and the driver's MPG calculations.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data<-}\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Data/mpg..csv"}\NormalTok{)}
\KeywordTok{round}\NormalTok{(}\KeywordTok{mean}\NormalTok{(data}\OperatorTok{$}\NormalTok{difference),}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.73
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{sd}\NormalTok{(data}\OperatorTok{$}\NormalTok{difference),}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.802
\end{verbatim}

\begin{itemize}
\tightlist
\item
  The sample mean of the difference is 2.73 miles per gallon with a
  standard deviation of 2.802 miles per gallon.
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{data,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\NormalTok{difference))}\OperatorTok{+}
\StringTok{       }\KeywordTok{geom_boxplot}\NormalTok{(}\DataTypeTok{fill=}\StringTok{"cornflowerblue"}\NormalTok{)}\OperatorTok{+}
\StringTok{       }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Difference in Miles Per Gallon (MPG)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW1_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  H\textsubscript{0}: The difference in MPG = 0;
\item
  H\textsubscript{a}: The difference in MPG \(\ne0\)
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(data}\OperatorTok{$}\NormalTok{difference, }\DataTypeTok{mu=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  data$difference
## t = 4.358, df = 19, p-value = 0.0003386
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  1.418847 4.041153
## sample estimates:
## mean of x 
##      2.73
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\item
\end{enumerate}

\begin{itemize}
\tightlist
\item
  We can conclude there is very strong evidence to reject the null
  hypothesis that there is no difference between the MPG provided by the
  VW onboard computer and the driver's calculation, and that there is
  very strong evidence supporting the alternative hypothesis that the
  true mean difference in MPG values between the VW computer and the
  driver's calculation is not equal to 0.
\end{itemize}


\end{document}
